export const PHONE = "529988450533";
export const BUSINESS_EMAIL = "jill@cancunpicnic.com";

export const COUNTRY_CODES = [
  { code: "+1", country: "US", flag: "🇺🇸", label: "United States" },
  { code: "+1", country: "CA", flag: "🇨🇦", label: "Canada" },
  { code: "+52", country: "MX", flag: "🇲🇽", label: "Mexico" },
  { code: "+44", country: "GB", flag: "🇬🇧", label: "United Kingdom" },
  { code: "+33", country: "FR", flag: "🇫🇷", label: "France" },
  { code: "+49", country: "DE", flag: "🇩🇪", label: "Germany" },
  { code: "+34", country: "ES", flag: "🇪🇸", label: "Spain" },
  { code: "+39", country: "IT", flag: "🇮🇹", label: "Italy" },
  { code: "+31", country: "NL", flag: "🇳🇱", label: "Netherlands" },
  { code: "+32", country: "BE", flag: "🇧🇪", label: "Belgium" },
  { code: "+41", country: "CH", flag: "🇨🇭", label: "Switzerland" },
  { code: "+43", country: "AT", flag: "🇦🇹", label: "Austria" },
  { code: "+46", country: "SE", flag: "🇸🇪", label: "Sweden" },
  { code: "+47", country: "NO", flag: "🇳🇴", label: "Norway" },
  { code: "+45", country: "DK", flag: "🇩🇰", label: "Denmark" },
  { code: "+358", country: "FI", flag: "🇫🇮", label: "Finland" },
  { code: "+353", country: "IE", flag: "🇮🇪", label: "Ireland" },
  { code: "+351", country: "PT", flag: "🇵🇹", label: "Portugal" },
  { code: "+48", country: "PL", flag: "🇵🇱", label: "Poland" },
  { code: "+420", country: "CZ", flag: "🇨🇿", label: "Czech Republic" },
  { code: "+36", country: "HU", flag: "🇭🇺", label: "Hungary" },
  { code: "+40", country: "RO", flag: "🇷🇴", label: "Romania" },
  { code: "+30", country: "GR", flag: "🇬🇷", label: "Greece" },
  { code: "+90", country: "TR", flag: "🇹🇷", label: "Turkey" },
  { code: "+7", country: "RU", flag: "🇷🇺", label: "Russia" },
  { code: "+380", country: "UA", flag: "🇺🇦", label: "Ukraine" },
  { code: "+55", country: "BR", flag: "🇧🇷", label: "Brazil" },
  { code: "+54", country: "AR", flag: "🇦🇷", label: "Argentina" },
  { code: "+56", country: "CL", flag: "🇨🇱", label: "Chile" },
  { code: "+57", country: "CO", flag: "🇨🇴", label: "Colombia" },
  { code: "+51", country: "PE", flag: "🇵🇪", label: "Peru" },
  { code: "+58", country: "VE", flag: "🇻🇪", label: "Venezuela" },
  { code: "+593", country: "EC", flag: "🇪🇨", label: "Ecuador" },
  { code: "+591", country: "BO", flag: "🇧🇴", label: "Bolivia" },
  { code: "+595", country: "PY", flag: "🇵🇾", label: "Paraguay" },
  { code: "+598", country: "UY", flag: "🇺🇾", label: "Uruguay" },
  { code: "+506", country: "CR", flag: "🇨🇷", label: "Costa Rica" },
  { code: "+507", country: "PA", flag: "🇵🇦", label: "Panama" },
  { code: "+502", country: "GT", flag: "🇬🇹", label: "Guatemala" },
  { code: "+503", country: "SV", flag: "🇸🇻", label: "El Salvador" },
  { code: "+504", country: "HN", flag: "🇭🇳", label: "Honduras" },
  { code: "+505", country: "NI", flag: "🇳🇮", label: "Nicaragua" },
  { code: "+501", country: "BZ", flag: "🇧🇿", label: "Belize" },
  { code: "+509", country: "HT", flag: "🇭🇹", label: "Haiti" },
  { code: "+1809", country: "DO", flag: "🇩🇴", label: "Dominican Republic" },
  { code: "+53", country: "CU", flag: "🇨🇺", label: "Cuba" },
  { code: "+1876", country: "JM", flag: "🇯🇲", label: "Jamaica" },
  { code: "+1868", country: "TT", flag: "🇹🇹", label: "Trinidad and Tobago" },
  { code: "+1242", country: "BS", flag: "🇧🇸", label: "Bahamas" },
  { code: "+1246", country: "BB", flag: "🇧🇧", label: "Barbados" },
  { code: "+61", country: "AU", flag: "🇦🇺", label: "Australia" },
  { code: "+64", country: "NZ", flag: "🇳🇿", label: "New Zealand" },
  { code: "+81", country: "JP", flag: "🇯🇵", label: "Japan" },
  { code: "+82", country: "KR", flag: "🇰🇷", label: "South Korea" },
  { code: "+86", country: "CN", flag: "🇨🇳", label: "China" },
  { code: "+852", country: "HK", flag: "🇭🇰", label: "Hong Kong" },
  { code: "+886", country: "TW", flag: "🇹🇼", label: "Taiwan" },
  { code: "+65", country: "SG", flag: "🇸🇬", label: "Singapore" },
  { code: "+60", country: "MY", flag: "🇲🇾", label: "Malaysia" },
  { code: "+66", country: "TH", flag: "🇹🇭", label: "Thailand" },
  { code: "+84", country: "VN", flag: "🇻🇳", label: "Vietnam" },
  { code: "+63", country: "PH", flag: "🇵🇭", label: "Philippines" },
  { code: "+62", country: "ID", flag: "🇮🇩", label: "Indonesia" },
  { code: "+91", country: "IN", flag: "🇮🇳", label: "India" },
  { code: "+92", country: "PK", flag: "🇵🇰", label: "Pakistan" },
  { code: "+880", country: "BD", flag: "🇧🇩", label: "Bangladesh" },
  { code: "+94", country: "LK", flag: "🇱🇰", label: "Sri Lanka" },
  { code: "+977", country: "NP", flag: "🇳🇵", label: "Nepal" },
  { code: "+971", country: "AE", flag: "🇦🇪", label: "United Arab Emirates" },
  { code: "+966", country: "SA", flag: "🇸🇦", label: "Saudi Arabia" },
  { code: "+974", country: "QA", flag: "🇶🇦", label: "Qatar" },
  { code: "+973", country: "BH", flag: "🇧🇭", label: "Bahrain" },
  { code: "+968", country: "OM", flag: "🇴🇲", label: "Oman" },
  { code: "+965", country: "KW", flag: "🇰🇼", label: "Kuwait" },
  { code: "+962", country: "JO", flag: "🇯🇴", label: "Jordan" },
  { code: "+961", country: "LB", flag: "🇱🇧", label: "Lebanon" },
  { code: "+972", country: "IL", flag: "🇮🇱", label: "Israel" },
  { code: "+20", country: "EG", flag: "🇪🇬", label: "Egypt" },
  { code: "+212", country: "MA", flag: "🇲🇦", label: "Morocco" },
  { code: "+216", country: "TN", flag: "🇹🇳", label: "Tunisia" },
  { code: "+213", country: "DZ", flag: "🇩🇿", label: "Algeria" },
  { code: "+234", country: "NG", flag: "🇳🇬", label: "Nigeria" },
  { code: "+233", country: "GH", flag: "🇬🇭", label: "Ghana" },
  { code: "+254", country: "KE", flag: "🇰🇪", label: "Kenya" },
  { code: "+27", country: "ZA", flag: "🇿🇦", label: "South Africa" },
  { code: "+255", country: "TZ", flag: "🇹🇿", label: "Tanzania" },
  { code: "+256", country: "UG", flag: "🇺🇬", label: "Uganda" },
  { code: "+251", country: "ET", flag: "🇪🇹", label: "Ethiopia" },
  { code: "+237", country: "CM", flag: "🇨🇲", label: "Cameroon" },
  { code: "+225", country: "CI", flag: "🇨🇮", label: "Ivory Coast" },
  { code: "+221", country: "SN", flag: "🇸🇳", label: "Senegal" },
  { code: "+354", country: "IS", flag: "🇮🇸", label: "Iceland" },
  { code: "+372", country: "EE", flag: "🇪🇪", label: "Estonia" },
  { code: "+371", country: "LV", flag: "🇱🇻", label: "Latvia" },
  { code: "+370", country: "LT", flag: "🇱🇹", label: "Lithuania" },
  { code: "+385", country: "HR", flag: "🇭🇷", label: "Croatia" },
  { code: "+386", country: "SI", flag: "🇸🇮", label: "Slovenia" },
  { code: "+421", country: "SK", flag: "🇸🇰", label: "Slovakia" },
  { code: "+359", country: "BG", flag: "🇧🇬", label: "Bulgaria" },
  { code: "+381", country: "RS", flag: "🇷🇸", label: "Serbia" },
  { code: "+352", country: "LU", flag: "🇱🇺", label: "Luxembourg" },
  { code: "+356", country: "MT", flag: "🇲🇹", label: "Malta" },
  { code: "+357", country: "CY", flag: "🇨🇾", label: "Cyprus" },
];

export const IMG = {
  hero: "https://cancunpicnic.com/wp-content/uploads/2023/07/Cancun-Photographer_3031.jpg",
  beach: "https://cancunpicnic.com/wp-content/uploads/2023/07/Cancun-Photographer_3028-768x512.jpg",
  lagoon: "https://cancunpicnic.com/wp-content/uploads/2023/07/Cancun-Photographer_3024-1-scaled.jpg",
  rooftop: "https://cancunpicnic.com/wp-content/uploads/2023/07/Cancun-Photographer_3025-1.jpg",
  bigLetters: "https://images.unsplash.com/photo-1522673607200-164d1b6ce486?w=600&q=80",
  medLettersFull: "https://images.unsplash.com/photo-1519741497674-611481863552?w=600&q=80",
  medLettersShort: "https://images.unsplash.com/photo-1519741497674-611481863552?w=600&q=80",
  stackedLetters: "https://images.unsplash.com/photo-1529636798458-92182e662485?w=600&q=80",
  flowerHeart: "https://images.unsplash.com/photo-1490750967868-88aa4f44baee?w=600&q=80",
  candleHeart: "https://images.unsplash.com/photo-1475721027785-f74eccf877e2?w=600&q=80",
  neonSign: "https://images.unsplash.com/photo-1516967124798-10656f7dca28?w=600&q=80",
  keepSimple: "https://cancunpicnic.com/wp-content/uploads/2023/07/Cancun-Photographer_3031.jpg",
  picnic: "https://images.unsplash.com/photo-1526234362653-3b75a0c07438?w=600&q=80",
  dinner: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=600&q=80",
  musician: "https://images.unsplash.com/photo-1511192336575-5a79af67a629?w=600&q=80",
  mariachi: "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=600&q=80",
  photo30: "https://images.unsplash.com/photo-1519741497674-611481863552?w=600&q=80",
  photo60: "https://images.unsplash.com/photo-1519741497674-611481863552?w=600&q=80",
  video30: "https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?w=600&q=80",
  video60: "https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?w=600&q=80",
  drone: "https://images.unsplash.com/photo-1473968512647-3e447244af8f?w=600&q=80",
  bouquet: "https://images.unsplash.com/photo-1490750967868-88aa4f44baee?w=600&q=80",
  petals: "https://images.unsplash.com/photo-1518621736915-f3b1c41bfd00?w=600&q=80",
  arr4: "https://images.unsplash.com/photo-1490750967868-88aa4f44baee?w=600&q=80",
  arr8: "https://images.unsplash.com/photo-1490750967868-88aa4f44baee?w=600&q=80",
  roses50: "https://images.unsplash.com/photo-1490750967868-88aa4f44baee?w=600&q=80",
  roses100: "https://images.unsplash.com/photo-1490750967868-88aa4f44baee?w=600&q=80",
  woodenFrame: "https://images.unsplash.com/photo-1519167758481-83f550bb49b3?w=600&q=80",
  gazeboStructure: "https://images.unsplash.com/photo-1519741497674-611481863552?w=600&q=80",
  metalStructure: "https://images.unsplash.com/photo-1490750967868-88aa4f44baee?w=600&q=80",
  structureNeon: "https://images.unsplash.com/photo-1516967124798-10656f7dca28?w=600&q=80",
  sparklers2: "https://images.unsplash.com/photo-1481162854517-d9e353af153d?w=600&q=80",
  sparklers4: "https://images.unsplash.com/photo-1481162854517-d9e353af153d?w=600&q=80",
  sparklers6: "https://images.unsplash.com/photo-1481162854517-d9e353af153d?w=600&q=80",
  sparklers8: "https://images.unsplash.com/photo-1481162854517-d9e353af153d?w=600&q=80",
  gazebo: "https://images.unsplash.com/photo-1519167758481-83f550bb49b3?w=600&q=80",
  teepee: "https://images.unsplash.com/photo-1478131143081-80f7f84ca84d?w=600&q=80",
};

export const VENUES = [
  { id: "beach", name: "Beach", price: 450, img: IMG.beach, badge: "SIGNATURE", desc: "Our beachfront location with stunning ocean views. Weekdays recommended for a more intimate experience.", priv: false },
  { id: "lagoon", name: "Lagoon", price: 350, img: IMG.lagoon, badge: "BEST VALUE", desc: "A private waterfront setting with the best sunset view in Cancun.", priv: true },
  { id: "rooftop", name: "Rooftop", price: 450, img: IMG.rooftop, badge: "PRIVATE", desc: "City skyline, ferris wheel, and panoramic sunset views. Truly unforgettable.", priv: true },
];

export const CENTERPIECES = [
  { id: "big-letters", name: 'Big Letters "MARRY ME"', price: 625, img: IMG.bigLetters, desc: "6ft tall, 25ft wide — our biggest statement piece", badge: "MOST POPULAR" },
  { id: "med-letters-full", name: '"Will You Marry Me?"', price: 495, img: IMG.medLettersFull, desc: "2ft letters on risers, standing 4ft high" },
  { id: "med-letters-short", name: '"Marry Me?"', price: 350, img: IMG.medLettersShort, desc: "2ft letters on risers — clean and classic" },
  { id: "stacked-letters", name: "Stacked Letters", price: 350, img: IMG.stackedLetters, desc: "6ft tall stacked display — elegant and intimate" },
  { id: "flower-structure", name: "Flower Design", price: 625, img: IMG.flowerHeart, desc: "400 fresh roses shaped into a heart, ring, or circle" },
];

export const ACTIVITIES = [
  { id: "picnic", name: "Romantic Picnic", price: 250, img: IMG.picnic, desc: "Curated charcuterie spread for two with a complimentary bottle of wine, styled at your venue" },
  { id: "dinner", name: "Candlelit Dinner", price: 250, img: IMG.dinner, desc: "Intimate 3-course dinner for two with a complimentary glass of wine under the stars" },
];

export const FLOWERS = [
  { id: "bouquet", name: "Rose Bouquet", price: 99, img: IMG.bouquet, desc: "3 dozen fresh roses — the first gift after saying yes", badge: "POPULAR" },
  { id: "petals", name: "Rose Petal Walkway", price: 50, img: IMG.petals, desc: "2 bags of red rose petals for a romantic walkway" },
  { id: "arrangements", name: "Flower Arrangements", pricePerUnit: 120, unitStep: 1, unitMin: 1, img: IMG.arr4, desc: "Elegant arrangements around your setup — 2 arrangements per bundle, $120 each", qty: true, perBundle: 2 },
  { id: "standing-roses", name: "Standing Roses", pricePerUnit: 60, unitStep: 1, unitMin: 1, img: IMG.roses50, desc: "Roses in sand lining your walkway — 24 roses per bundle, $60 each", qty: true, perBundle: 24, bundleUnit: "roses" },
  { id: "candle-heart", name: "Candle Heart", price: 150, img: IMG.candleHeart, desc: "LED candles and rose petals — beautifully simple" },
];

export const STRUCTURES = [
  { id: "wooden-frame", name: "Wooden Structure / Giant Frame", price: 150, img: IMG.woodenFrame, desc: "Wooden Gazebo or Giant Frame w/ fabric and lighting. Add a Neon sign and florals to complete the look" },
  { id: "gazebo-structure", name: "Gazebo Structure", price: 200, img: IMG.gazeboStructure, desc: "Wooden Gazebo w/ fabric and lighting. Add a Neon sign and florals to complete the look" },
  { id: "metal-structure", name: "Metal Structures (Heart, Circle or Rectangle)", price: 100, img: IMG.metalStructure, desc: "Choose from our selection of metal structures. This simple structure can be taken to the next level with fabric, Neon sign and florals" },
  { id: "structure-neon", name: "Neon Sign", price: 125, img: IMG.structureNeon, desc: "Add a glowing neon sign to your structure" },
  { id: "teepee", name: "Boho TeePee", price: 150, img: IMG.teepee, desc: "12ft teepee with hanging spheres and boho arrangement" },
];

export const STRUCTURE_NEON_MESSAGES = [
  "Will you marry me?", "It was always you", "Te casas conmigo?",
  "Will you be my Wife?", "This is our love story", "Let's grow old together",
  "You & Me", "She said yes",
];

export const WOW = [];

export const SPARKLER_PRICES = { 0: 0, 2: 225, 4: 330, 6: 435, 8: 540 };
export const SPARKLER_MAX = 8;

export const PORTFOLIO = [
  { img: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80", venue: "beach", centerpiece: "big-letters", time: "sunset", flowers: [], wow: [] },
  { img: "https://images.unsplash.com/photo-1495616811223-4d98c6e9c869?w=800&q=80", venue: "beach", centerpiece: "big-letters", time: "sunset", flowers: ["petals"], wow: ["sparklers-2"] },
  { img: "https://images.unsplash.com/photo-1475721027785-f74eccf877e2?w=800&q=80", venue: "beach", centerpiece: "big-letters", time: "evening", flowers: [], wow: [] },
  { img: "https://images.unsplash.com/photo-1510414842594-a61c69b5ae57?w=800&q=80", venue: "beach", centerpiece: "flower-structure", time: "sunset", flowers: [], wow: [] },
  { img: "https://images.unsplash.com/photo-1519046904884-53103b34b206?w=800&q=80", venue: "beach", centerpiece: "none", time: "evening", flowers: ["candle-heart"], wow: [] },
  { img: "https://images.unsplash.com/photo-1506953823976-52e1fdc0149a?w=800&q=80", venue: "beach", centerpiece: "none", time: "sunset", flowers: ["petals", "candle-heart"], wow: [] },
  { img: "https://images.unsplash.com/photo-1471922694854-ff1b63b20054?w=800&q=80", venue: "beach", centerpiece: "none", time: "evening", flowers: [], wow: [] },
  { img: "https://images.unsplash.com/photo-1473116763249-2faaef81ccda?w=800&q=80", venue: "beach", centerpiece: "none", time: "sunset", flowers: [], wow: [] },
  { img: "https://images.unsplash.com/photo-1433086966358-54859d0ed716?w=800&q=80", venue: "lagoon", centerpiece: "big-letters", time: "sunset", flowers: [], wow: [] },
  { img: "https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?w=800&q=80", venue: "lagoon", centerpiece: "big-letters", time: "sunset", flowers: [], wow: ["sparklers-2"] },
  { img: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=800&q=80", venue: "lagoon", centerpiece: "flower-structure", time: "sunset", flowers: [], wow: [] },
  { img: "https://images.unsplash.com/photo-1518548419970-58e3b4079ab2?w=800&q=80", venue: "lagoon", centerpiece: "none", time: "evening", flowers: ["bouquet", "candle-heart"], wow: [] },
  { img: "https://images.unsplash.com/photo-1439066615861-d1af74d74000?w=800&q=80", venue: "lagoon", centerpiece: "stacked-letters", time: "sunset", flowers: [], wow: [] },
  { img: "https://images.unsplash.com/photo-1444492417251-9c84a5fa18e0?w=800&q=80", venue: "lagoon", centerpiece: "none", time: "sunset", flowers: [], wow: [] },
  { img: "https://images.unsplash.com/photo-1519167758481-83f550bb49b3?w=800&q=80", venue: "rooftop", centerpiece: "big-letters", time: "evening", flowers: [], wow: [] },
  { img: "https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?w=800&q=80", venue: "rooftop", centerpiece: "big-letters", time: "evening", flowers: [], wow: ["sparklers-2"] },
  { img: "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=800&q=80", venue: "rooftop", centerpiece: "none", time: "evening", flowers: [], wow: [] },
  { img: "https://images.unsplash.com/photo-1478131143081-80f7f84ca84d?w=800&q=80", venue: "rooftop", centerpiece: "none", time: "evening", flowers: ["candle-heart"], wow: [], structures: ["teepee"] },
  { img: "https://images.unsplash.com/photo-1490750967868-88aa4f44baee?w=800&q=80", venue: "rooftop", centerpiece: "flower-structure", time: "sunset", flowers: [], wow: [] },
  { img: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&q=80", venue: "rooftop", centerpiece: "none", time: "evening", flowers: [], wow: [] },
];

export const ADDONS = {
  music: [
    { id: "solo-musician", name: "Solo Musician", price: 295, img: IMG.musician, desc: "Sax, guitar, violin, cello, or harp — 30-45 min" },
    { id: "mariachi", name: "Mariachi Band", price: 325, img: IMG.mariachi, desc: "5-6 musicians, 7 songs — 25-30 min" },
  ],
  capture: [
    { id: "photo-30", name: "Photography (30 min)", price: 295, img: IMG.photo30, desc: "50 digital images — proposal + mini engagement session" },
    { id: "photo-60", name: "Photography (60 min)", price: 350, img: IMG.photo60, desc: "100 digital images — full proposal + extended shoot" },
    { id: "video-30", name: "Video (30 min)", price: 325, img: IMG.video30, desc: "2-3 minute professionally edited proposal video" },
    { id: "video-60", name: "Video (60 min)", price: 375, img: IMG.video60, desc: "5-8 minute cinematic proposal film" },
    { id: "drone", name: "Drone Footage", price: 150, img: IMG.drone, desc: "Aerial footage add-on — stunning bird's eye views" },
  ],
};

export const NEON_MESSAGES = [
  "Will you marry me?", "It was always you", "Te casas conmigo?", "Marry me?",
  "This is our love story", "Let's grow old together", "You & Me", "They said yes",
];

export const SOCIAL_PROOF = {
  venue: {
    headline: "What 1,500+ couples chose",
    stats: [{ label: "chose Beach", pct: 68 }, { label: "chose Rooftop", pct: 19 }, { label: "chose Lagoon", pct: 13 }],
    tip: "Beach is our signature — but Lagoon has the best sunset views and total privacy.",
  },
  centerpiece: {
    headline: "Most popular setups",
    stats: [{ label: "pick Big Letters", pct: 45 }, { label: "pick Flower Design", pct: 22 }, { label: "pick Neon Sign", pct: 15 }],
    tip: "Big Letters creates the most dramatic reaction when your partner turns around.",
  },
  addons: {
    headline: "What others add to their proposal",
    stats: [{ label: "add Photography", pct: 94 }, { label: "add Video", pct: 52 }, { label: "add a Musician", pct: 44 }],
    tip: "The #1 regret we hear? 'I wish I had gotten photos.'",
  },
};

export const PACKAGES = [
  {
    id: "simple",
    name: "Simple & Sweet",
    price: 850,
    badge: "INTIMATE",
    desc: "An intimate and romantic proposal experience designed to let the moment speak for itself. Featuring soft candlelight, elegant roses, and a beautifully styled setting for just the two of you.",
    includes: ["Venue of your choice", "Candle Heart setup", "Rose Bouquet (3 dozen)", "Rose Petal Walkway", "Coordination · 1.5 hrs · Sparkling wine · Server"],
    imgs: [
      "https://images.unsplash.com/photo-1519046904884-53103b34b206?w=800&q=80",
      "https://images.unsplash.com/photo-1506953823976-52e1fdc0149a?w=800&q=80",
      "https://images.unsplash.com/photo-1518548419970-58e3b4079ab2?w=800&q=80",
    ],
  },
  {
    id: "glamorous",
    name: "Glamorous",
    price: 1500,
    badge: "MOST POPULAR",
    desc: "A show-stopping proposal experience designed to leave a lasting impression. Featuring bold statement lettering, glowing sparklers, and elegantly styled roses, every detail is thoughtfully designed to take their breath away.",
    includes: ["Venue of your choice", 'Big Letters "MARRY ME"', "Rose Bouquet (3 dozen)", "Rose Petal Walkway", "Fountain Sparklers (x4)", "Coordination · 1.5 hrs · Sparkling wine · Server"],
    imgs: [
      "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80",
      "https://images.unsplash.com/photo-1495616811223-4d98c6e9c869?w=800&q=80",
      "https://images.unsplash.com/photo-1519167758481-83f550bb49b3?w=800&q=80",
    ],
  },
  {
    id: "artist",
    name: "Artist Touch",
    price: 2200,
    badge: "PREMIUM",
    desc: "Our signature luxury experience, created for those who expect nothing but the exceptional. With over 10 years of expertise, we curate an unforgettable, bespoke moment for your special partner — one that will be remembered forever.",
    includes: ["Venue of your choice", 'Big Letters "MARRY ME"', "Flower Heart Design (400 roses)", "100 Standing Roses", "Fountain Sparklers (x4)", "Wooden Structure with lighting", "Coordination · 1.5 hrs · Sparkling wine · Server"],
    imgs: [
      "https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?w=800&q=80",
      "https://images.unsplash.com/photo-1433086966358-54859d0ed716?w=800&q=80",
      "https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=800&q=80",
    ],
  },
];
